version: '2'
services:
  db:
    image: postgres
  backend:
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000"
    depends_on:
      - db
    links:
      - db
  frontend:
    build: frontend
    volumes:
      - ./frontend:/code
    ports:
      - "8000"
  nginx:
    build: nginx
    ports:
      - "8000:8000"
    depends_on:
      - backend
      - frontend
    links:
      - backend
